"""add queue issue type relationship

Revision ID: 0352989c4918
Revises: 1ec9c7890d6d
Create Date: 2026-09-22 17:26:13.092628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0352989c4918'
down_revision: Union[str, Sequence[str], None] = '1ec9c7890d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_queues_issue_types',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('issue_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('queue_id', 'issue_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_queues_issue_types')
    # ### end Alembic commands ###
