"""Add multiple relationships to Tickets table

Revision ID: 0b43f50ed34b
Revises: b14ecb1d25a0
Create Date: 2026-07-29 16:53:11.297065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b43f50ed34b'
down_revision: Union[str, Sequence[str], None] = 'b14ecb1d25a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_body', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('additional_notes', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'issue_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tickets', 'short_issue',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'troubleshooting_steps',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tickets', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'priority_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'generated_ticket',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tickets', 'generated_time_entry',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tickets', 'is_routed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tickets', 'is_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tickets', 'generated_status_time_entry',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tickets', 'issue_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'form_template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'troubleshooting_template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'queue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tickets', 'queue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'troubleshooting_template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'form_template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'issue_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'generated_status_time_entry',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'is_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tickets', 'is_routed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tickets', 'generated_time_entry',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'generated_ticket',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'priority_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'troubleshooting_steps',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'short_issue',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tickets', 'issue_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tickets', 'closed_at')
    op.drop_column('tickets', 'additional_notes')
    op.drop_column('tickets', 'ticket_body')
    # ### end Alembic commands ###
