"""Create ticket knowledge base relation

Revision ID: 1ec9c7890d6d
Revises: 6efbdf17280f
Create Date: 2026-09-03 13:22:42.328564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec9c7890d6d'
down_revision: Union[str, Sequence[str], None] = '6efbdf17280f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_tickets_knowledge_base',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'knowledge_base_id')
    )
    op.drop_constraint(op.f('tickets_kb_article_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'kb_article_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('kb_article_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tickets_kb_article_id_fkey'), 'tickets', 'knowledge_base', ['kb_article_id'], ['id'])
    op.drop_table('relation_tickets_knowledge_base')
    # ### end Alembic commands ###
