"""Create relation issue types knowledge base table, and create relation between issue types and forms

Revision ID: 20ed1692c100
Revises: 7a7553f817c8
Create Date: 2026-07-24 16:52:48.389728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ed1692c100'
down_revision: Union[str, Sequence[str], None] = '7a7553f817c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_issue_types_knowledge_base',
    sa.Column('issue_type_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('issue_type_id', 'knowledge_base_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_issue_types_knowledge_base')
    # ### end Alembic commands ###
