"""add access request and password reset to tools

Revision ID: 3dba98f076bd
Revises: 0352989c4918
Create Date: 2026-09-22 18:36:16.368388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dba98f076bd'
down_revision: Union[str, Sequence[str], None] = '0352989c4918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('access_request', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('password_reset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'password_reset')
    op.drop_column('tools', 'access_request')
    # ### end Alembic commands ###
