"""Add form content to tickets

Revision ID: 6efbdf17280f
Revises: 0b43f50ed34b
Create Date: 2026-08-28 12:50:59.010347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efbdf17280f'
down_revision: Union[str, Sequence[str], None] = '0b43f50ed34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('form_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'form_content')
    # ### end Alembic commands ###
