"""Add created_by field to several tables and create WHS Systems table with relationship to Locations

Revision ID: 7a7553f817c8
Revises: ddd68277629d
Create Date: 2026-07-23 19:37:22.200452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7553f817c8'
down_revision: Union[str, Sequence[str], None] = 'ddd68277629d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whs_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('form_fields', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'form_fields', 'users', ['created_by'], ['id'])
    op.add_column('forms', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'forms', 'users', ['created_by'], ['id'])
    op.add_column('issue_types', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'issue_types', 'users', ['created_by'], ['id'])
    op.add_column('knowledge_base', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'knowledge_base', 'users', ['created_by'], ['id'])
    op.add_column('locations', sa.Column('state', sa.String(), nullable=False))
    op.add_column('locations', sa.Column('code', sa.String(), nullable=False))
    op.add_column('locations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('locations', sa.Column('whs_system_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locations', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'locations', 'whs_systems', ['whs_system_id'], ['id'])
    op.drop_column('locations', 'country')
    op.add_column('priorities', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'priorities', 'users', ['created_by'], ['id'])
    op.add_column('queues', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'queues', 'users', ['created_by'], ['id'])
    op.add_column('ticket_status', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ticket_status', 'users', ['created_by'], ['id'])
    op.add_column('tools', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tools', 'users', ['created_by'], ['id'])
    op.add_column('troubleshooting_templates', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'troubleshooting_templates', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'troubleshooting_templates', type_='foreignkey')
    op.drop_column('troubleshooting_templates', 'created_by')
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.drop_column('tools', 'created_by')
    op.drop_constraint(None, 'ticket_status', type_='foreignkey')
    op.drop_column('ticket_status', 'created_by')
    op.drop_constraint(None, 'queues', type_='foreignkey')
    op.drop_column('queues', 'created_by')
    op.drop_constraint(None, 'priorities', type_='foreignkey')
    op.drop_column('priorities', 'created_by')
    op.add_column('locations', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'whs_system_id')
    op.drop_column('locations', 'created_by')
    op.drop_column('locations', 'is_active')
    op.drop_column('locations', 'code')
    op.drop_column('locations', 'state')
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.drop_column('knowledge_base', 'created_by')
    op.drop_constraint(None, 'issue_types', type_='foreignkey')
    op.drop_column('issue_types', 'created_by')
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_column('forms', 'created_by')
    op.drop_constraint(None, 'form_fields', type_='foreignkey')
    op.drop_column('form_fields', 'created_by')
    op.drop_table('whs_systems')
    # ### end Alembic commands ###
