"""add issue type knowledge base note relationship

Revision ID: 84d2cc9509ae
Revises: f3b8af8ea5eb
Create Date: 2026-09-23 19:13:26.844835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d2cc9509ae'
down_revision: Union[str, Sequence[str], None] = 'f3b8af8ea5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_issue_types_knowledge_base_notes',
    sa.Column('issue_type_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_note_id'], ['knowledge_base_notes.id'], ),
    sa.PrimaryKeyConstraint('issue_type_id', 'knowledge_base_note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_issue_types_knowledge_base_notes')
    # ### end Alembic commands ###
