"""Add name to Troubleshooting Templates table

Revision ID: b14ecb1d25a0
Revises: f7cbe02566ab
Create Date: 2026-07-29 12:43:06.768669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14ecb1d25a0'
down_revision: Union[str, Sequence[str], None] = 'f7cbe02566ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('troubleshooting_templates', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('troubleshooting_templates', 'name')
    # ### end Alembic commands ###
