"""Create issue configuration tables

Revision ID: ddd68277629d
Revises: e7b59ddc44ab
Create Date: 2026-07-20 19:43:57.516499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd68277629d'
down_revision: Union[str, Sequence[str], None] = 'e7b59ddc44ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_id'), 'forms', ['id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priorities_id'), 'priorities', ['id'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queues_id'), 'queues', ['id'], unique=False)
    op.create_table('ticket_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_id'), 'ticket_status', ['id'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_table('troubleshooting_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('generated_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_troubleshooting_templates_id'), 'troubleshooting_templates', ['id'], unique=False)
    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_fields_id'), 'form_fields', ['id'], unique=False)
    op.create_table('issue_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('form_template_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('search_keywords', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_template_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_types_id'), 'issue_types', ['id'], unique=False)
    op.create_table('relation_knowledge_base_tools',
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('knowledge_base_id', 'tool_id')
    )
    op.create_table('relation_troubleshooting_templates_knowledge_base',
    sa.Column('troubleshooting_template_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['troubleshooting_template_id'], ['troubleshooting_templates.id'], ),
    sa.PrimaryKeyConstraint('troubleshooting_template_id', 'knowledge_base_id')
    )
    op.create_table('relation_troubleshooting_templates_tools',
    sa.Column('troubleshooting_template_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['troubleshooting_template_id'], ['troubleshooting_templates.id'], ),
    sa.PrimaryKeyConstraint('troubleshooting_template_id', 'tool_id')
    )
    op.create_table('relation_issue_types_tools',
    sa.Column('issue_type_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('issue_type_id', 'tool_id')
    )
    op.create_table('relation_issue_types_troubleshooting_templates',
    sa.Column('issue_type_id', sa.Integer(), nullable=False),
    sa.Column('troubleshooting_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], ),
    sa.ForeignKeyConstraint(['troubleshooting_template_id'], ['troubleshooting_templates.id'], ),
    sa.PrimaryKeyConstraint('issue_type_id', 'troubleshooting_template_id')
    )
    op.add_column('tickets', sa.Column('tool_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('short_issue', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('location_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('priority_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('generated_ticket', sa.Text(), nullable=False))
    op.add_column('tickets', sa.Column('generated_time_entry', sa.Text(), nullable=False))
    op.add_column('tickets', sa.Column('is_routed', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('is_status', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('generated_status_time_entry', sa.Text(), nullable=False))
    op.add_column('tickets', sa.Column('issue_type_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('kb_article_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('form_template_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('troubleshooting_template_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('status_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('queue_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tickets', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('tickets', 'issue_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('tickets', 'troubleshooting_steps',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('tickets_user_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tickets', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'forms', ['form_template_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'tools', ['tool_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'queues', ['queue_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'ticket_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'priorities', ['priority_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'issue_types', ['issue_type_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'troubleshooting_templates', ['troubleshooting_template_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'knowledge_base', ['kb_article_id'], ['id'])
    op.drop_column('tickets', 'location')
    op.drop_column('tickets', 'kb')
    op.drop_column('tickets', 'user_id')
    op.drop_column('tickets', 'issue')
    op.drop_column('tickets', 'content')
    op.drop_column('tickets', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('issue', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('kb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_user_id_fkey'), 'tickets', 'users', ['user_id'], ['id'])
    op.alter_column('tickets', 'troubleshooting_steps',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('tickets', 'issue_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'created_by')
    op.drop_column('tickets', 'created_at')
    op.drop_column('tickets', 'queue_id')
    op.drop_column('tickets', 'status_id')
    op.drop_column('tickets', 'troubleshooting_template_id')
    op.drop_column('tickets', 'form_template_id')
    op.drop_column('tickets', 'kb_article_id')
    op.drop_column('tickets', 'issue_type_id')
    op.drop_column('tickets', 'generated_status_time_entry')
    op.drop_column('tickets', 'is_status')
    op.drop_column('tickets', 'is_routed')
    op.drop_column('tickets', 'generated_time_entry')
    op.drop_column('tickets', 'generated_ticket')
    op.drop_column('tickets', 'priority_id')
    op.drop_column('tickets', 'location_id')
    op.drop_column('tickets', 'short_issue')
    op.drop_column('tickets', 'tool_id')
    op.drop_table('relation_issue_types_troubleshooting_templates')
    op.drop_table('relation_issue_types_tools')
    op.drop_table('relation_troubleshooting_templates_tools')
    op.drop_table('relation_troubleshooting_templates_knowledge_base')
    op.drop_table('relation_knowledge_base_tools')
    op.drop_index(op.f('ix_issue_types_id'), table_name='issue_types')
    op.drop_table('issue_types')
    op.drop_index(op.f('ix_form_fields_id'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_troubleshooting_templates_id'), table_name='troubleshooting_templates')
    op.drop_table('troubleshooting_templates')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_ticket_status_id'), table_name='ticket_status')
    op.drop_table('ticket_status')
    op.drop_index(op.f('ix_queues_id'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_priorities_id'), table_name='priorities')
    op.drop_table('priorities')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_forms_id'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
