"""Remove unique constraint from ticket_number

Revision ID: e7b59ddc44ab
Revises: 2fa61fd45ed9
Create Date: 2026-07-17 18:24:01.833980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b59ddc44ab'
down_revision: Union[str, Sequence[str], None] = '2fa61fd45ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
