"""add knowledge base notes

Revision ID: f3b8af8ea5eb
Revises: 184f4fe7443e
Create Date: 2026-09-23 16:55:15.876415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b8af8ea5eb'
down_revision: Union[str, Sequence[str], None] = '184f4fe7443e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_notes_id'), 'knowledge_base_notes', ['id'], unique=False)
    op.create_table('relation_tools_knowledge_base_notes',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_note_id'], ['knowledge_base_notes.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('tool_id', 'knowledge_base_note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_tools_knowledge_base_notes')
    op.drop_index(op.f('ix_knowledge_base_notes_id'), table_name='knowledge_base_notes')
    op.drop_table('knowledge_base_notes')
    # ### end Alembic commands ###
