"""Create warehouse management systems table

Revision ID: f7cbe02566ab
Revises: 20ed1692c100
Create Date: 2026-07-28 17:11:29.118436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cbe02566ab'
down_revision: Union[str, Sequence[str], None] = '20ed1692c100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_management_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('locations', sa.Column('warehouse_management_system_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('locations_whs_system_id_fkey'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'warehouse_management_systems', ['warehouse_management_system_id'], ['id'])
    op.drop_column('locations', 'whs_system_id')
    op.drop_table('whs_systems')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('whs_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_whs_system_id_fkey'), 'locations', 'whs_systems', ['whs_system_id'], ['id'])
    op.drop_column('locations', 'warehouse_management_system_id')
    op.create_table('whs_systems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('whs_systems_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('whs_systems_pkey'))
    )
    op.drop_table('warehouse_management_systems')
    # ### end Alembic commands ###
